"""dbt-forge cost — CLI command for query cost estimation."""

from __future__ import annotations

from rich.console import Console
from rich.table import Table

from dbt_forge.cost import ADAPTER_STATS_FN, SUPPORTED_ADAPTERS, CostReport
from dbt_forge.introspect.connectors import get_introspector
from dbt_forge.introspect.profile_reader import read_profile
from dbt_forge.scanner import find_project_root

console = Console()


def run_cost(
    days: int = 30,
    top: int = 10,
    report: bool = False,
    target: str = "dev",
) -> None:
    """Run cost analysis against the warehouse."""
    root = find_project_root()

    try:
        profile = read_profile(root, target=target)
    except Exception as e:
        console.print(f"[red]Error reading profile:[/red] {e}")
        return

    adapter = profile.get("type", "")
    if adapter not in SUPPORTED_ADAPTERS:
        console.print(
            f"[yellow]Cost analysis not yet supported for '{adapter}'.[/yellow]\n"
            f"Supported adapters: {', '.join(SUPPORTED_ADAPTERS)}"
        )
        return

    try:
        introspector = get_introspector(adapter, **profile)
        introspector.connect()
    except Exception as e:
        console.print(f"[red]Error connecting to warehouse:[/red] {e}")
        return

    try:
        stats_fn = ADAPTER_STATS_FN[adapter]
        stats = stats_fn(introspector, days)
    except Exception as e:
        console.print(f"[red]Error retrieving cost data:[/red] {e}")
        return
    finally:
        introspector.close()

    if not stats:
        console.print("[green]No query stats found for the given period.[/green]")
        return

    cost_report = CostReport(stats=stats)
    top_models = cost_report.top_n(top)

    if report:
        _render_markdown_report(cost_report, top_models, days)
    else:
        _render_table(cost_report, top_models, days)


def _render_table(cost_report: CostReport, top_models: list, days: int) -> None:
    """Render cost table with Rich."""
    console.print()
    table = Table(
        title=f"dbt-forge cost (last {days} days)",
        show_lines=False,
        padding=(0, 1),
    )
    table.add_column("Model", min_width=20)
    table.add_column("Bytes Scanned", justify="right")
    table.add_column("Avg Duration", justify="right")
    table.add_column("Executions", justify="right")
    table.add_column("Est. Cost (USD)", justify="right")

    for stat in top_models:
        bytes_str = _format_bytes(stat.total_bytes_scanned)
        duration_str = f"{stat.avg_duration_seconds:.1f}s"
        cost_str = f"${stat.estimated_cost_usd:.2f}"
        table.add_row(
            stat.model_name,
            bytes_str,
            duration_str,
            str(stat.execution_count),
            cost_str,
        )

    console.print(table)
    console.print()
    console.print(f"  [bold]Total estimated cost:[/bold] ${cost_report.total_estimated_cost:.2f}")
    console.print()

    # Materialization suggestions
    suggestions = cost_report.materialization_suggestions()
    if suggestions:
        console.print("[bold cyan]Materialization suggestions:[/bold cyan]")
        for s in suggestions[:5]:
            console.print(
                f"  {s['model']}: {s['current']} -> [bold]{s['suggested']}[/bold] ({s['reason']})"
            )
        console.print()


def _render_markdown_report(cost_report: CostReport, top_models: list, days: int) -> None:
    """Render cost report as markdown."""
    lines = [
        f"# Cost Report (last {days} days)",
        "",
        f"**Total estimated cost:** ${cost_report.total_estimated_cost:.2f}",
        "",
        "| Model | Bytes Scanned | Avg Duration | Executions | Est. Cost |",
        "|-------|---------------|--------------|------------|-----------|",
    ]
    for stat in top_models:
        lines.append(
            f"| {stat.model_name} | {_format_bytes(stat.total_bytes_scanned)} "
            f"| {stat.avg_duration_seconds:.1f}s "
            f"| {stat.execution_count} "
            f"| ${stat.estimated_cost_usd:.2f} |"
        )

    suggestions = cost_report.materialization_suggestions()
    if suggestions:
        lines.extend(["", "## Materialization Suggestions", ""])
        for s in suggestions[:5]:
            lines.append(f"- **{s['model']}**: {s['current']} -> {s['suggested']} ({s['reason']})")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by `dbt-forge cost`*")
    console.print("\n".join(lines))


def _format_bytes(n: int) -> str:
    """Format byte count to human-readable."""
    if n == 0:
        return "0 B"
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if abs(n) < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} PB"
