"""dbt-forge impact — change impact analysis."""

from __future__ import annotations

import subprocess
from pathlib import Path

from rich.console import Console
from rich.tree import Tree

from dbt_forge.ref_graph import RefGraph, build_ref_graph, get_all_downstream
from dbt_forge.scanner import find_project_root, parse_yml_tests
from dbt_forge.ui.theme import make_table, print_error, print_warning, timed

console = Console()


def _get_changed_models_from_git(root: Path, base_ref: str) -> list[str]:
    """Get model names changed between base_ref and HEAD."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", f"{base_ref}...HEAD", "--", "models/"],
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return []
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return []

    changed = []
    for line in result.stdout.strip().splitlines():
        line = line.strip()
        if line.endswith(".sql"):
            name = Path(line).stem
            changed.append(name)
    return changed


def _build_impact_tree(graph: RefGraph, model: str) -> Tree:
    """Build a Rich Tree showing downstream impact, colored by depth."""
    tree = Tree(f"[bold]{model}[/bold]")
    downstream = get_all_downstream(graph, model)

    # Group by depth
    by_depth: dict[int, list[str]] = {}
    for name, depth in downstream.items():
        by_depth.setdefault(depth, []).append(name)

    def _add_children(parent_tree: Tree, parent_name: str, current_depth: int) -> None:
        for child in sorted(graph.downstream.get(parent_name, set())):
            if child in downstream:
                depth = downstream[child]
                if depth == 1:
                    style = "red"
                elif depth == 2:
                    style = "yellow"
                else:
                    style = "green"
                child_tree = parent_tree.add(f"[{style}]{child}[/{style}]")
                _add_children(child_tree, child, depth)

    _add_children(tree, model, 0)
    return tree


def _compute_blast_radius(graph: RefGraph, changed: list[str], tested: set[str]) -> dict:
    """Compute blast radius stats for changed models."""
    all_impacted: set[str] = set()
    direct: set[str] = set()
    transitive: set[str] = set()

    for model in changed:
        downstream = get_all_downstream(graph, model)
        for name, depth in downstream.items():
            all_impacted.add(name)
            if depth == 1:
                direct.add(name)
            else:
                transitive.add(name)

    total_models = len(graph.nodes)
    untested = {m for m in all_impacted if m not in tested}
    blast_pct = (len(all_impacted) / total_models * 100) if total_models > 0 else 0

    return {
        "total_impacted": len(all_impacted),
        "direct": len(direct),
        "transitive": len(transitive),
        "untested_count": len(untested),
        "untested_models": sorted(untested),
        "blast_pct": round(blast_pct, 1),
    }


def _render_pr_markdown(graph: RefGraph, changed: list[str], blast: dict) -> str:
    """Render a markdown summary for PR descriptions."""
    lines = [
        "## Impact Analysis",
        "",
        f"**Changed models:** {', '.join(f'`{m}`' for m in changed)}",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total impacted | {blast['total_impacted']} |",
        f"| Direct dependents | {blast['direct']} |",
        f"| Transitive dependents | {blast['transitive']} |",
        f"| Untested impacted | {blast['untested_count']} |",
        f"| Blast radius | {blast['blast_pct']}% |",
        "",
    ]

    if blast["untested_models"]:
        lines.append("**Untested impacted models:**")
        for m in blast["untested_models"][:10]:
            lines.append(f"- `{m}`")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by `dbt-forge impact`*")
    return "\n".join(lines)


def run_impact(
    model: str | None = None,
    diff: bool = False,
    base: str = "main",
    pr: bool = False,
) -> None:
    """Run impact analysis."""
    root = find_project_root()
    graph = build_ref_graph(root)

    changed: list[str] = []

    if diff:
        with timed("Detecting changed models from git..."):
            changed = _get_changed_models_from_git(root, base)
        if not changed:
            print_warning("No changed models found in git diff.")
            return
        console.print(f"[bold]Changed models:[/bold] {', '.join(changed)}")
        console.print()
    elif model:
        if model not in graph.nodes:
            print_error(f"Model '{model}' not found in project.")
            return
        changed = [model]
    else:
        print_error("Provide a model name or use --diff.")
        return

    tested = parse_yml_tests(root)
    blast = _compute_blast_radius(graph, changed, tested)

    if pr:
        md = _render_pr_markdown(graph, changed, blast)
        console.print(md)
        return

    # Display impact trees
    for m in changed:
        if m not in graph.nodes:
            print_warning(f"'{m}' not found in graph, skipping.")
            continue
        tree = _build_impact_tree(graph, m)
        console.print(tree)
        console.print()

    # Summary table
    table = make_table("Blast Radius", [
        ("Metric", {"min_width": 20}),
        ("Value", {"justify": "right"}),
    ])
    table.add_row("Total impacted", str(blast["total_impacted"]))
    table.add_row("Direct dependents", str(blast["direct"]))
    table.add_row("Transitive dependents", str(blast["transitive"]))
    table.add_row("Untested impacted", str(blast["untested_count"]))
    table.add_row("Blast radius", f"{blast['blast_pct']}%")
    console.print(table)
    console.print()

    if blast["untested_models"]:
        console.print("[yellow]Untested impacted models:[/yellow]")
        for m in blast["untested_models"][:10]:
            console.print(f"  - {m}")
        console.print()
