"""dbt-forge update — re-apply templates to an existing project."""

from __future__ import annotations

import difflib

import questionary
from rich.console import Console
from rich.syntax import Syntax

from dbt_forge.generator.project import generate_project
from dbt_forge.manifest import (
    MANIFEST_FILE,
    dict_to_config,
    read_manifest,
    write_manifest,
)
from dbt_forge.scanner import find_project_root

console = Console()


def run_update(dry_run: bool = False) -> None:
    """Re-render templates and offer to update changed files."""
    root = find_project_root()
    manifest = read_manifest(root)

    if manifest is None:
        console.print(
            f"[red]Error:[/red] No [bold]{MANIFEST_FILE}[/bold] found.\n"
            "This project was not generated by dbt-forge (or was generated before "
            "the update feature). Run [cyan]dbt-forge init[/cyan] to create a new project."
        )
        return

    # Reconstruct config
    config = dict_to_config(manifest.config)
    config.output_dir = str(root.parent)

    # Generate to a temp location to get rendered content
    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        config_copy = dict_to_config(manifest.config)
        config_copy.output_dir = tmpdir
        rendered_files = generate_project(config_copy, dry_run=False)

        import os

        tmp_base = os.path.join(tmpdir, config.project_name)

        changed = []
        unchanged = []
        new_files = []

        for rendered_path in rendered_files:
            try:
                rel = str(rendered_path.relative_to(tmp_base))
            except ValueError:
                continue
            if rel == MANIFEST_FILE:
                continue

            rendered_content = rendered_path.read_text() if rendered_path.exists() else ""
            existing_path = root / rel

            if not existing_path.exists():
                new_files.append((rel, rendered_content))
                continue

            existing_content = existing_path.read_text()
            if existing_content == rendered_content:
                unchanged.append(rel)
            else:
                changed.append((rel, existing_content, rendered_content))

    console.print()
    console.print(f"  [bold cyan]dbt-forge update[/bold cyan] — {root.name}")
    console.print()
    console.print(f"  [green]{len(unchanged)}[/green] unchanged")
    console.print(f"  [yellow]{len(changed)}[/yellow] changed")
    console.print(f"  [blue]{len(new_files)}[/blue] new")
    console.print()

    if not changed and not new_files:
        console.print("  [dim]Everything is up to date.[/dim]")
        console.print()
        return

    if dry_run:
        if changed:
            console.print("[bold]Changed files:[/bold]")
            for rel, old, new in changed:
                console.print(f"  [yellow]M[/yellow]  {rel}")
                diff = difflib.unified_diff(
                    old.splitlines(keepends=True),
                    new.splitlines(keepends=True),
                    fromfile=f"a/{rel}",
                    tofile=f"b/{rel}",
                    n=3,
                )
                diff_text = "".join(diff)
                if diff_text:
                    console.print(Syntax(diff_text, "diff", theme="monokai"))
        if new_files:
            console.print("[bold]New files:[/bold]")
            for rel, _ in new_files:
                console.print(f"  [blue]A[/blue]  {rel}")
        console.print()
        return

    # Interactive mode
    accepted_files: list[str] = []

    for rel, old, new in changed:
        console.print(f"\n[bold]--- {rel} ---[/bold]")
        diff = difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"a/{rel}",
            tofile=f"b/{rel}",
            n=3,
        )
        diff_text = "".join(diff)
        if diff_text:
            console.print(Syntax(diff_text, "diff", theme="monokai"))

        action = questionary.select(
            f"Apply changes to {rel}?",
            choices=["accept", "skip"],
            style=questionary.Style(
                [
                    ("qmark", "fg:#00d7ff bold"),
                    ("question", "bold"),
                    ("pointer", "fg:#00d7ff bold"),
                ]
            ),
        ).ask()
        if action == "accept":
            (root / rel).write_text(new)
            accepted_files.append(rel)
            console.print(f"  [green]✔[/green]  Updated {rel}")
        else:
            console.print(f"  [dim]Skipped {rel}[/dim]")

    for rel, content in new_files:
        action = questionary.select(
            f"Create new file {rel}?",
            choices=["accept", "skip"],
            style=questionary.Style(
                [
                    ("qmark", "fg:#00d7ff bold"),
                    ("question", "bold"),
                    ("pointer", "fg:#00d7ff bold"),
                ]
            ),
        ).ask()
        if action == "accept":
            dest = root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content)
            accepted_files.append(rel)
            console.print(f"  [green]✔[/green]  Created {rel}")
        else:
            console.print(f"  [dim]Skipped {rel}[/dim]")

    if accepted_files:
        # Re-generate manifest with current files
        all_files = [root / f for f in manifest.files if (root / f).exists()]
        write_manifest(root, config, all_files)
        console.print(f"\n  [bold]{len(accepted_files)}[/bold] file(s) updated.")
    else:
        console.print("\n  [dim]No changes applied.[/dim]")
    console.print()
